#define BTHOME_BTN_NONE 0x00
#define BTHOME_BTN_PRESS 0x01
#define BTHOME_BTN_DOUBLE_PRESS 0x02
#define BTHOME_BTN_TRIPLE_PRESS 0x03
#define BTHOME_BTN_LONG_PRESS 0x04
#define BTHOME_BTN_LONG_DOUBLE_PRESS 0x05
#define BTHOME_BTN_LONG_TRIPLE_PRESS 0x06
#define BTHOME_BTN_HOLD_PRESS 0x80
